# Generated by Django 2.2.3 on 2019-07-01 15:27

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True, validators=[account.models.validate_num]),
        ),
    ]
